# Permalinks
permalink:           pretty

# Setup
title:               Hannah M. Lewis
tagline:             Astronomy PhD turned Data Scientist
url:                 http://hmlewis-astro.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Hannah Lewis
  #url:               https://www.linkedin.com/in/hmlewis-astro/
  #email:             hanlewis528@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/hmlewis-astro

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'

theme: jekyll-theme-slate